# Generated by Django 5.0.6 on 2024-05-21 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
        ('Rss', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='feeds',
            field=models.ManyToManyField(blank=True, help_text='Источники, к которым пользователь подписан', related_name='users', to='Rss.feed', verbose_name='Источники'),
        ),
    ]
