# Generated by Django 5.0.6 on 2024-08-19 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rss', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='icon',
            field=models.URLField(blank=True, help_text='Иконка статьи', null=True, verbose_name='Иконка'),
        ),
    ]
